### ISSUE TITLE
full backup crashes iOS

### ISSUE THREAD

**Issue by thedavidmeister** [byteball/obyte-gui-wallet#171]
Not sure what happened but my phone froze and then crashed the app when i tried to do a full export.

Setting the password seemed to be OK, but it was when i actually tried to get the export that it crashed.

Maybe https://github.com/byteball/byteball/issues/170 might help, but i dunno?

**Comment by Xeerie** [comment]
Crash is due to a lack of memory, seems memory leak, or just not optimized memory management.
I have had restarted the app and it loaded with wallet fully restored.iPhone 7 with  iOS 10.3.2.
I also tried restore wallet on iPad Pro with iOS 11 developer beta with no success, backup file just wont import. Looks like new file management in iOS 11 is incompatible with many third-party apps.

**Comment by tonyofbyteball** [comment]
Backup in iOS was significantly updated, please reopen the issue if it persists.
