### ISSUE TITLE
Uncaught exception: Error: Error: SQLITE_ERROR: too many SQL variables

### ISSUE THREAD

**Issue by berbant** [byteball/obyte-gui-wallet#265]
v.2.0.0, W10, full wallet:
Uncaught exception: Error: Error: SQLITE_ERROR: too many SQL variables UPDATE units SET main_chain_index=? WHERE unit IN(?) 1516549, uwMEv2SLrhNU...
at 12/9/17 12:53.

**Comment by fiskadoro** [comment]
Same here. It was syncing for a few days from scratch and nearly finished, now hanging on this error at around the time 2 days ago when I transferred some funds into this wallet, before it was finished sync-ing. Which was apparently a bad idea since now the funds are stuck in nirvana while this newly created full wallet is unable to see the transfer as it won't sync beyond the point of when then funds were transferred into it.

**Comment by fiskadoro** [comment]
Actually, didn't see that before, I'm stuck on the exact same piece of data: 

WHERE unit IN(?) 1516549, uwMEv2SLrhNUrnH47k+O7e8+XvjRdsayYzRqPZ/UbHU=, ...

so it must affect others too? Just to reiterate, it's like with the OP, Windows 10, v2.0.0, full wallet.

**Comment by MeredithRodneyMcKay** [comment]
I just want to point out that this wallet behaviour renders the wallet completely useless, since i forgot to mention it before.
- Wallet Startup.
- You start typing your password.
- Boom. Non-closable error window.
I'm literally cut off of my Byteball funds at the moment because of this and anyone else with this problem too.

**Comment by becksteiner** [comment]
Hello, 
I have the same error. Does someone has a solution what to do? I don't want to loose all my byteballs :-(

**Comment by tonyofbyteball** [comment]
It was fixed in more recent versions.
