### ISSUE TITLE
wallet not working under fedora since may 2018

### ISSUE THREAD

**Issue by schollinator** [byteball/obyte-gui-wallet#364]
wallet will not launch without any error message under fedora 28. this problem has been ongoing for more than 2 months...

**Comment by yeswecoin** [comment]
Same for me on Manjaro 17.1 with kernel 4.17.9.

This is the error message in the commandline:
```
LaunchProcess: failed to execvp:
/usr/share/byteball/nacl_helper
[18413:18413:0727/213546:ERROR:nacl_fork_delegate_linux.cc(315)] Bad NaCl helper startup ack (0 bytes
```
Does anyone knows how to fix that?

Thanks

**Comment by develroo** [comment]
I think it is broken across all distros. Segfaults too here on Debian on a 4.17.8-1 (2018-07-20) kernel.

A question I would like to ask is has anyone managed to compile it themselves using the build instructions because that seems not to work either. 

Methinks someone needs to start on converting it to a snap or something.

**Comment by schollinator** [comment]
this project needs more devs instead of some cringy marketing...

**Comment by schollinator** [comment]
@tonyofbyteball

**Comment by schollinator** [comment]
https://www.youtube.com/watch?v=Tqy4cAQVzLU

**Comment by FredericS2018** [comment]
@schollinator here are some instructions I received on Byteball slack, have not yet tested them:

1) `mkdir byteball-wallet` to create a new project folder
2) `cd byteball-wallet`
3) `git clone git@github.com:byteball/byteball.git .`
4) `npm install`
5) copy folders from installed wallet sqlite folder `C:\Program Files (x86)\Byteball\node_modules\sqlite3\lib\binding` to project `node_modules\sqlite3\lib\binding` folder.
6) `grunt desktop` - this installs nwjs to `cache\0.14.7\win64` project folder and builds the executable to project's parent folder at `.\byteballbuilds\Byteball\win64`
7) you can either copy `node_modules` to `.\byteballbuilds\Byteball\win64\node_modules` and start a wallet from that folder or you can just run `cache/0.14.7/win64/nw.exe .` in project folder
paths are bit different on Linux, but otherwise steps should be same.

**Comment by schollinator** [comment]
4.npm install throws a ton of errors....

npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated coffee-script@1.8.0: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated uws@9.14.0: stop using this version
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
npm WARN deprecated minimatch@0.4.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/byteball/byteballcore.git /root/.npm/_cacache/tmp/git-clone-3c0f69d1
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-3c0f69d1': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-03T10_44_17_094Z-debug.log

**Comment by FredericS2018** [comment]
Hi again @schollinator,

I've not yet gotten around to this still. I should have tagged @tarmo888 the first time around as he was the one who gave me the instructions on slack.

**Comment by FredericS2018** [comment]
here is my updated issue. After trying your instructions @tarmo888 (all except #5, I don't think sqlite was an issue for me) I try to rerun ./Byteball in the byteball-builds folder, the client loads but is blank, the error code returned is: ``/home/frederic/byteballbuilds/Byteball/linux64/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:12
    throw new Error(message);
    ^
Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (/home/frederic/byteballbuilds/Byteball/linux64/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:12:11)
    at Object.<anonymous> (/home/frederic/byteballbuilds/Byteball/linux64/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:15:9)
    at Module._compile (module.js:437:34)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:381:32)
    at Function.Module._load (module.js:338:12)
    at Module.require (module.js:391:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/frederic/byteballbuilds/Byteball/linux64/node_modules/bitcore-mnemonic/lib/mnemonic.js:3:15)
    at Module._compile (module.js:437:34)``

And using npm find-dupes bitcore-lib initially told me to remove minimatch	3.0.4	node_modules/istanbul/node_modules/minimatch, which I did, but is now not telling me anything's wrong, while the error message when running ./Byteball persists.

**Comment by tarmo888** [comment]
I don't have a linux installed, so I am afraid I have no idea why it is doing that :(
Is downloadable linux release working on your machine? https://github.com/byteball/byteball/releases

**Comment by FredericS2018** [comment]
Thank you Tarmo. That seems to have done the trick for me

**Comment by n-ric-v** [comment]
First :

I hope you have a copy of your wallet.

Then, open a terminal. We have to clean old shits. Type :

rm -R .node-gyp && rm -R .npm && rm -R nw-gyp

if one of above folders are missing, better for you, less work.

Then, just in case install missing packages, type :

su -c 'dnf install gtk2 gtk3 libcanberra openssl pkgconfig gcc g++ python make nodejs npm -y'

Since Fedora 27, the nodejs module version should be the 64 or 59 on non updated Fed, so, download the NW.JS 0.36.4. I use a library folder... so
mkdir library && cd library

if your machine is a 64 bits :
wget "https://dl.nwjs.io/v0.36.4/nwjs-v0.36.4-linux-x64.tar.gz"

or 32 bits :
wget "https://dl.nwjs.io/v0.36.4/nwjs-v0.36.4-linux-ia32.tar.gz"

tar xvzf nwjs-v0.36.4-linux-x64.tar.gz && rm nwjs-v0.36.4-linux-x64.tar.gz
or
tar xvzf nwjs-v0.36.4-linux-ia32.tar.gz && rm nwjs-v0.36.4-linux-ia32.tar.gz

mkdir Obyte && cd Obyte && git clone https://github.com/byteball/obyte-gui-wallet.git && cd obyte-gui-wallet/ && gedit Gruntfile.js

In the Gruntfile.js, edit the line 228 and change the version of NW.JS : 0.36.4 instead of 0.14.7. Save and close

by the way, security policy doesn't allow to use the "-g" command with npm. Then type into the terminal : 
npm install nw-gyp
export npm_config_target=0.36.4
export npm_config_arch=x64
export npm_config_target_arch=x64
export npm_config_runtime=node-webkit
export npm_config_build_from_source=true

From now, ignore warnings and errors

npm install bower
npm install grunt-cli
bower install
npm install
grunt

./../nwjs-v0.36.4-linux-x64/nw .
or
./../nwjs-v0.36.4-linux-ia32/nw .

if the wallets starts, your on the good way to finalize your installation

mkdir ../obytebuilds
grunt desktop
cp -R node_modules/ ../obytebuilds/Obyte/linux64/
grunt linux64

And you have finish. Your wallet is in the obytebuilds directory.
cd ../obytebuilds/Obyte/linux64

**Comment by tarmo888** [comment]
There is AppImage for Linux now, which should help to get it working on more Linux distros https://github.com/byteball/obyte-gui-wallet/releases
