### ISSUE TITLE
Not easy to try it out

### ISSUE THREAD

**Issue by xiongzhend** [byteball/obyte-gui-wallet#398]
the install instruction is not clear, I followed the steps but not work.
1. I checkout the testnet
2. I run "bower install" && "npm install" && "grunt"
3. I don't know how to run it, so I tried to "grunt desktop", and it creates a byteballbuilds and when I double click the "/byteballbuilds/Byteball-TN/osx64/Byteball-TN", it is a blank window

I don't know if I need to run some kind of server first or else?

**Comment by zhang0135789** [comment]
please look at the README. There are answers you want know


zz634682577@163.com
 
From: 咸虾高怕飞
Date: 2018-11-08 09:31
To: byteball/byteball
CC: Subscribed
Subject: [byteball/byteball] Not easy to try it out (#398)
the install instruction is not clear, I followed the steps but not work.
I checkout the testnet
I run "bower install" && "npm install" && "grunt"
I don't know how to run it, so I tried to "grunt desktop", and it creates a byteballbuilds and when I double click the "/byteballbuilds/Byteball-TN/osx64/Byteball-TN", it is a blank window
I don't know if I need to run some kind of server first or else?

**Comment by xiongzhend** [comment]
thanks for the quick reply, is it your QQ number?

**Comment by xiongzhend** [comment]
Btw, I downloaded mainnet, and testnet wallet from website, the syncing is always 0

**Comment by zhang0135789** [comment]
you could contact me by my 163 email


zz634682577@163.com
 
From: 咸虾高怕飞
Date: 2018-11-08 09:47
To: byteball/byteball
CC: zz; Comment
Subject: Re: [byteball/byteball] Not easy to try it out (#398)
Btw, I downloaded mainnet, and testnet wallet from website, the syncing is always 0

**Comment by xiongzhend** [comment]
ok, thanks

**Comment by xiongzhend** [comment]
not solve yet, any one help?

**Comment by Papabyte** [comment]
Are you on MacOS or Linux?

**Comment by tarmo888** [comment]
Most likely you get the blank window because it's looking for the node_sqlite3.node in wrong place. 

https://github.com/byteball/byteball/blob/master/README.md
README.md has explanation how to solve this, but if you still can't resolve the issue then it would be best if you join Byteball community on Slack and ask help from #helpdesk channel. https://slack.byteball.org/

**Comment by xiongzhend** [comment]
> Are you on MacOS or Linux?

both macos and windows

**Comment by xiongzhend** [comment]
> Most likely you get the blank window because it's looking for the node_sqlite3.node in wrong place.
> 
> https://github.com/byteball/byteball/blob/master/README.md
> README.md has explanation how to solve this, but if you still can't resolve the issue then it would be best if you join Byteball community on Slack and ask help from #helpdesk or #tech channel. https://slack.byteball.org/

I have look through it many times, and maybe I am not clear, blank is not literally blank, it has something on the app but not sync at all

**Comment by tarmo888** [comment]
You could also right click on anywhere and click "Inspect" from menu and then check out if there is any errors in Console.

**Comment by xiongzhend** [comment]
I use "inspect" and on the "network" tab is empty...

**Comment by xiongzhend** [comment]
on my mac, there is no error but always sync 0...
<img width="1574" alt="d1e6f94a-0fc2-4f8d-a3c1-4675210ff84f" src="https://user-images.githubusercontent.com/214743/49002883-ba24d100-f19b-11e8-9794-b4ba39e8de77.png">

**Comment by xiongzhend** [comment]
on my windows, there is one error and not even sync...
![_20181126165013](https://user-images.githubusercontent.com/214743/49002961-eb050600-f19b-11e8-9863-0d2109ab5c5a.jpg)

**Comment by tarmo888** [comment]
On Mac, did you picked full node, so it has not finished syncing. Does the "syncing..." message ever go away? Full wallet sync can take quite a lot of time for the first time and you don't really need full node on your wallet. If you need full node for development of a bot then it is easier to have that separate as headless-byteball.

I am guessing you have picked full node on Windows too? Not sure what causes the error with the language file because it should load zh_CN.json instead.

**Comment by xiongzhend** [comment]
I picked full node, the syncing message never go away. OK, if syncing first time will take a lot of time, I tried run for a whole night but still the same, and as you can see, network is empty, no package comes and goes. Let me try not full node this time.

**Comment by xiongzhend** [comment]
I tried no full node, it is nothing happen, maybe you can send me a little tiny 0.0001 coin to test if it works, many thanks.

**Comment by tarmo888** [comment]
Not sure what you mean by "always",  if you sync it once and don't delete the data folder then it will continue syncing where it left off next time. So if you now synced all 33GB and then don't use it for a month and if DAG has grown 1GB then your wallet needs to sync only the additional 1GB.

If you use light node then you don't have to sync so much data at all because it will only keep data that is relevant to your wallet. That's why, for GUI wallet, it makes sense to use light node, but for headless-wallet, it makes sense to sync full node.

With testnet, there is a faucet on that page, click on it and it should open the testnet wallet where you can get free bytes for testing https://byteball.org/testnet.html

**Comment by NOZHENHAO-123** [comment]
楼主在Windows上，能否运行？
我在windows上，也遇到同样的问题了，整了一天的环境，还没有弄好。
