### ISSUE TITLE
Ask users to back up before creating an account

### ISSUE THREAD

**Issue by shadutopian** [byteball/obyte-gui-wallet#465]
I have used obyte wallet at the time when they generously airdropped obyte to steemians. I had a few bytes left in the wallet which were to be unlocked only after one year. I had somehow deleted the wallet so I installed it again and signed in with my steem account only to find that my funds were lost. 
I know that we can back up our wallet if we scroll through the menu but obyte is a wallet and the first thing they should ask users is to create a back up and not let any user use the wallet without back up. 
There are plenty of other cryptocurrency wallets which ask users to create back up first and like them obyte should do the same. Alternatively they can also send the backup via a file which can be saved locally.

**Comment by tarmo888** [comment]
There is also a downside for asking to backup as the first thing because starting using the wallet should be as easy as possible, without asking too much when they try it first time.
That's why, the latest 2.7.2 wallet is reminding the users to create the backup once they have some bytes already in their wallet. Full backup shouldn't be only saved locally, it should be backed up on a network drive or email too (full backup is encrypted with password).

**Comment by shadutopian** [comment]
I just send some funds to my wallet and it asked me to back up the wallet.
It is a much better approach. 
Though I lost my previous funds, but now I hope no one else will.
