### ISSUE TITLE
SHASUMS?

### ISSUE THREAD

**Issue by Emily7777** [byteball/obyte-gui-wallet#484]
Hi folks,

Where can I get the SHASUMS for the latest releases?

https://github.com/byteball/obyte-gui-wallet/releases

thanks

**Comment by tarmo888** [comment]
* Mac binaries are signed and doesn't need checksums.
* Windows binaries were signed, but 2.7.* are missing them because new certificate needs to be applied for.
* Linux binaries doesn't support signing.

Obyte doesn't use mirrors, you should download the binaries only from obyte.org or official Github repository, so checksum doesn't make much sense.
