### ISSUE TITLE
How to confirm unconfirmed transaction(fund) ?

### ISSUE THREAD

**Issue by Kuanhui** [byteball/obyte-gui-wallet#489]
I sent some funds to my phone app(gui-wallet)
and this is shown.
![image](https://user-images.githubusercontent.com/49285022/65046345-4a8ff600-d915-11e9-9e13-9412cc5bde6e.png)
but it is unconfirmed fund, so I can not send bytes to address.
Please help me.
Thanks.

**Comment by tarmo888** [comment]
It should confirm in 10-15 minutes, sometimes a little longer on Light wallets.

If you click on Unit ID, what does it show as status on explorer? If it shows bad unit or can't find the unit at all then you made a double-spend attempt and it will never confirm. This usually happens when you restore an old backup and trying to spend funds that are already spent.

**Comment by Kuanhui** [comment]
Thank you very much!!!
