### ISSUE TITLE
Recover blackbytes

### ISSUE THREAD

**Issue by FyreDemonyte** [byteball/obyte-gui-wallet#580]
I have an older wallet backup, and I haven't touched in some time, and have discovered due to one of the new wallet versions I could no longer access my blackbytes. 

Is there anyway to recover them ? 

I still have the SEED, and .encrypted backup file.

**The backup file is dated August 28, 2019.**

Please assist if you can. Thank you

**Comment by tarmo888** [comment]
What was the problem with that wallet version? If the problem was that the wallet app didn't work on older mac hardware then that is fixed on latest version that was just released https://github.com/byteball/obyte-gui-wallet/releases

Seed words don't recover Blackbytes (seed words recover only public data) and the .encrypted backup file must be created after the last time you sent/received Blackbytes. If you spent Blackbytes after creating the backup then they are lost.

**Comment by FyreDemonyte** [comment]
Ok so I just imported the encrypted file and it worked with the newest version. Both my GB and GBB balances are accounted for. 

I'm trying to remember where it was this became an issue. but it had to have been between version 2.7.0 and 2.8.0, where for some reason when I imported the encrypted backup my GBB were not appearing. 

But now in this newest version they do. So I'm happy now :100: 

Thanks for your help @tarmo888
